version: "3.8"

services:
  wireguard-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wireguard-manager
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /etc/wireguard:/etc/wireguard
    environment:
      - WG_AUTH_TOKEN=${WG_AUTH_TOKEN:-your-secure-token}
      - CLIENT_IPV4=${CLIENT_IPV4:-10.66.66.3}
      - CLIENT_IPV6=${CLIENT_IPV6:-fd42:42:42::3}
      - WG_PORT=${WG_PORT:-49321}
    cap_add:
      - NET_ADMIN
    network_mode: host
    privileged: true
